spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
Springdoc:
  openapi:
    title: 'Gerenciamento de Tarefas'
    description: 'API para gerenciamento de tarefas'
    version: '1.0.0'
